### ISSUE TITLE
when i run, dont build with error : ../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_chips_input-2.0.0/lib/src/chips_input.dart:87:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:  - TextInputClient.didChangeInputControl  - TextInputClient.performSelector

### ISSUE THREAD

**Issue by KhamdamovDilmurod** [itsarvinddev/map_location_picker#13]

**Comment by itsarvinddev** [comment]
Hi @KhamdamovDilmurod, Thank you for creating an issue and using this package.

This issue was caused by the `form_builder_extra_fields` package and I have made a pull request for the `form_builder_extra_fields` package
Made https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/pull/55
I am waiting for pull accept or merge.

For now you can use this package via Git:

```
  map_location_picker:
    git:
      url: https://github.com/rvndsngwn/map_location_picker.git
```

**Comment by itsarvinddev** [comment]
Version 1.2.0 released.
